### ISSUE TITLE
Some devices fail to load.

### ISSUE THREAD

**Issue by lexchoi0810** [mesmotronic/air-ane-fullscreen#18]
HI, I am happy to use your ANE and really appreciate your work!
I have found that using ANE causes lock up on some devices.
Following is the log:

※Log
[Starling] Initialization complete.
[Starling] Display Driver: OpenGL (Baseline Constrained)
[AssetManager] Looking for static embedded assets in 'TitleAsset'
[AssetManager] Enqueuing 'xml_title'
[AssetManager] Enqueuing 'title'
[AssetManager] Adding texture 'title'
[Starling] Initialization complete.
[Starling] Display Driver: OpenGL (Baseline Constrained)
status: notLicensed statusReason: +null

It seems Starling initialization is firing twice. 
Removing the ANE fixed the problem. (happening on Samsung Galaxy Note 2)

Please help!

**Comment by neilrackett** [comment]
This sounds similar to issue #19, so perhaps try the solution suggested by neolit123?
