### ISSUE TITLE
Samsung Galaxy S3 issues

### ISSUE THREAD

**Issue by neolit123** [mesmotronic/air-ane-fullscreen#19]
hello,

a test case on:
Samsung Galaxy S3 (I9300) (Android 4.3)

with an older version of the ANE you can hide the whole system UI, but after a while it suddenly shows the status bar.

with the latest ANE and AIR17 it doesn't hide the system UI at all.

any idea why that happens?
thanks

**Comment by neilrackett** [comment]
It sounds like the ANE isn't being embedded correctly in your AIR 17 build.

You should double check the ANE settings and ensure that both `AndroidFullScreen.isSupported` and `AndroidFullScreen.immersiveMode()` return `true`.

**Comment by wastedabuser** [comment]
Hi,

Keep in mind that some other ANE's or Android features may steal the focus from your application.
Be sure to capture the restore of the focus to your application by listening to an event:
```
NativeApplication.nativeApplication.addEventListener(AndroidFullScreen.ANDROID_WINDOW_FOCUS_IN, onFocusIn);
```

Regards,

**Comment by neolit123** [comment]
> It sounds like the ANE isn't being embedded correctly in your AIR 17 build.

the same APK runs fine, fullscreen on another device.

**Comment by neolit123** [comment]
> Keep in mind that some other ANE's or Android features may steal the focus from your application.
> Be sure to capture the restore of the focus to your application by listening to an event:

this is something i need to try.

**Comment by neolit123** [comment]
just tried adding the ANDROID_WINDOW_FOCUS_IN listener.

basically in the other thread i describe what is the current test app setup:
- Main.as calls immersiveMode() and the ANDROID_WINDOW_FOCUS_IN listener also calls it when triggered
- the initial flickering which is due to the resize handler is gone
- the native navigation bar is hidden (at the bottom) from immersiveMode(), but the status bar (at the top) is not.

could be some weird Samsung exclusive feature that causes that or perhaps a third party app that is running? any ideas?

**Comment by wastedabuser** [comment]
I had a similar issue with Galaxy S3 Neo. Using the latest ANE and the code i have pasted in #20 solved the issue... Well it refused to hide the bottom toolbar in my case. Some of my clients are reporting a black bar on the top. As i see it is not a task bar as it does not have the icons. Could you please attach a screenshot?
Please, show some of your code, as by your description we could only guess :(

**Comment by neolit123** [comment]
here it is:

```
package
{
	import flash.events.Event;
	import flash.display.Sprite;
	import flash.desktop.NativeApplication;
	
	import starling.core.Starling;

	import com.mesmotronic.ane.AndroidFullScreen;

	[SWF(width="450", height="800", frameRate="60", backgroundColor="#000000")]

	public class Main extends Sprite
	{
		public function Main():void
		{
			if (AndroidFullScreen.isSupported) {
				AndroidFullScreen.immersiveMode();
				NativeApplication.nativeApplication.addEventListener(AndroidFullScreen.ANDROID_WINDOW_FOCUS_IN, focusHandler);
			}

			// init Starling here
			// ...
		}

		private function focusHandler(_e:Event):void
		{
			AndroidFullScreen.immersiveMode();
		}
	}
}
```

**Comment by neolit123** [comment]
> Could you please attach a screenshot?
i can't ATM, but it's pretty much the native status bar. also i can confirm that no wierd applications are running at the same time as the test app. BTW fullscreen is not enabled in the app descriptor (<fullScreen>false</fullScreen>), not sure if that would make a difference...

**Comment by neilrackett** [comment]
Solution: use AIR 23 (see issue #32)
