### ISSUE TITLE
Error #3500: The extension context does not have a method with the name init.

### ISSUE THREAD

**Issue by fknr** [mesmotronic/air-ane-fullscreen#27]
I get this error when i try to use the extension:
Error #3500: The extension context does not have a method with the name init.

I am using:
AIR 20.0.0 build 233

Other extensions like milkmangames GoViral work fine. i get the same error when air-ane-fullscreen is the only ane in the project

when i replace the ane with v1.3.3 everything works fine

**Comment by tangamampilia** [comment]
Same here, happens with the last published ANE.

**Comment by neilrackett** [comment]
Can you confirm which version of Android you're using?

**Comment by fknr** [comment]
The error appears even before deploying the app to the device so i think the Android version does not matter.
There is no binary attached to the 1.4.0 realease. I only tested 1.4.1 and 1.3.3

**Comment by tangamampilia** [comment]
I tested with Android 4.2 and Adobe AIR 20 and 19. I used the last published ANE and the 1.3.3 works fine as fknr stated.

**Comment by neilrackett** [comment]
I've rebuilt and updated the 1.4.1 binary: can you try downloading the updated ANE and let me know if you're still seeing the issue? It seems to be working fine here on our test devices.

https://github.com/mesmotronic/air-ane-fullscreen/releases/tag/v1.4.1

**Comment by fknr** [comment]
I tested your new build but unfortunately i still get the same error when i try to build the app.

**Comment by neilrackett** [comment]
Thanks for taking a look.

Version 1.4.x targets Android SDK 23 (previous versions targeted 19), so does your `app.xml` include any target SDK settings in the Android `<manifestAdditions>`? It would looks something like this:

```xml
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" />
```

If so, can you let me know what the settings are that you're using? And if the `targetSdkVersion` is <23, can you try setting it to 23 and building your app?

**Comment by nitacawo** [comment]
Tested new build everything works fine for me. But I am building with adobe flash professional. (air sdk 21) Have been using your extension for quite a while so wanted to say thanks anyway :)

**Comment by neilrackett** [comment]
Cheers @nitacawo, thanks for letting me know.

**Comment by fknr** [comment]
I tested a little more and found out that the ane works on an actual device. the error only happens in emulator mode. 1.3.3 works in emulator mode. I think that changed when you consolidated the default SWC into single file.

in 1.3.3 you use

		static public function get isSupported():Boolean
		{
			return false;
		}

and in > 1.4.0 you use:

		static public function get isSupported():Boolean
		{
			return !!context;
		}

for now a simple workaround is to check

		public static function isAndroid():Boolean
		{
			return (Capabilities.version.substr(0, 3) == "AND");
		}

before calling isSupported() in my code

It would be cool if you could fix this in one of the next versions. Thanks for your effort in provding this  very helpful ane

**Comment by neilrackett** [comment]
Thanks for the info: should be an easy fix now we know what the problem is.
