### ISSUE TITLE
Remove navbar while keep transparent topbar.

### ISSUE THREAD

**Issue by serjek** [mesmotronic/air-ane-fullscreen#29]
What would it take to create a custom fullscreen display, like show transparent top bar and hide navbar entirely? To make it similar to what iOS has in 7+ versions: overlaying status bar with color provided by application and without navigation buttons.

**Comment by neilrackett** [comment]
It should be possible to [customise the UI visibility options](https://developer.android.com/reference/android/view/View.html#setSystemUiVisibility(int)) to display the application under the status bar with the navigation bar hidden, but having a transparent status bar might be more complicated as it would most likely require a style resource and possibly changes to the manifest. You might be able to achieve the same outcome using `Window.setStatusBarColor(int);`, but we had AIR packaging errors the last time we tried.

**Comment by serjek** [comment]
Actually setting status bar color is a nice-to-have feature, but not required. What I'm looking for is to toggle navbar visibility or remove it for good. I will check the article thanks. Perhaps any advice how would I tweak currently implemented functions to achieve requested arrangement without hassle? 

Initially my thinking was to duplicate the ShowUnderSystemUiFunction and see if there is a way to  set flags properly to remove navbar leaving content "under" and topbar as transparent - this would produce the desired effect. But it seem like this won't work.

**Comment by neilrackett** [comment]
Adding `View.SYSTEM_UI_FLAG_HIDE_NAVIGATION` to the `uiOptions` in `ShowUnderSystemUiFunction` will give you the layout you require:

```java
int uiOptions = 
	View.SYSTEM_UI_FLAG_LAYOUT_STABLE
	| View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
	| View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
	| View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN;
```

However, the navigation bar won't auto hide after a user re-opens it (drags from the side of the screen), so you will need to have a stage click handler (or similar) to ensure it's re-hidden when a user subsequently interacts with your app.

**Comment by serjek** [comment]
Right. As my app requires user to actively swipe on stage this approach won't work here. Navbar reappears on almost every touch. I wonder if there is a firm way to hide this bar for good.

**Comment by serjek** [comment]
All right, adding View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY flag solves the problem. Now I event don't have to bother with navbar overlapping the app, as it appears only briefly on swipe from side and is removed on stage tap, as intended. Thanks for this ANE!

**Comment by neilrackett** [comment]
:-)
