### ISSUE TITLE
Event for displaying system UI in immersive mode

### ISSUE THREAD

**Issue by serjek** [mesmotronic/air-ane-fullscreen#30]
Hi. How would I detect the system UI being displayed in immersive mode (when user swipes from side to display UI briefly)? This is required to rearrange app's UI a little - increase top padding in header so that system UI bar content won't entirely overlap my app's header icons.

**Comment by serjek** [comment]
I surely can detect swipes myself on app stage but this doesn't feel very native. So I'd stick to ANE events if possible.

**Comment by neilrackett** [comment]
This is not something that's currently supported by the ANE.

**Comment by serjek** [comment]
No problem, just wanted to make sure before attempting this myself as described here
https://developer.android.com/training/system-ui/visibility.html
Thanks!

**Comment by neilrackett** [comment]
Sounds like a useful feature!

You can see how the existing events work in `FullScreenContext.onWindowFocusChanged`, if that's any help, and there's already an `onSystemUiVisibilityChange` handler you can add your code to, starting at line 110 of `ImmersiveModeFunction`

**Comment by serjek** [comment]
Well. It seems temporarily displayed system UI doesn't count towards "visibility change", as Android event is not dispatched. Same occurs even in sample Android Studio projects, so I gave up on this.
