### ISSUE TITLE
ContextLoss on touch

### ISSUE THREAD

**Issue by metaine** [mesmotronic/air-ane-fullscreen#31]
Hi! Thanks for you efforts to develop this extension.
We use Starling fork in our project, and Fullscreen version 1.3. worked almost fine (except for crashes for some users). Have downloaded latest 1.4.7 version from github, and now we're facing lost context message in several cases (Starling handles the context loss, so user presented with the special screen while context is recovering, but it isn't shown when ANE Fullscreen 1.3 in use). I still can't understand what in my code could bring that to life.

**Comment by neilrackett** [comment]
It sounds like you are, but can you confirm that you're using `Starling.handleLostContext = true;`?

**Comment by metaine** [comment]
Yes I can confirm that.

**Comment by neilrackett** [comment]
Could you post a reduced test case?

Do you have any more information, for example which version of Android you're seeing this on and the AIR SDK you're using.

**Comment by metaine** [comment]
I'm working on reduced version for the moment, cant provide it yet.
Here what I've got for now: 

we initialize ANE that way: 
AndroidFullScreen.stage = stage;		
if(AndroidFullScreen.isSupported && AndroidFullScreen.isImmersiveModeSupported) 
	AndroidFullScreen.immersiveMode(false);

and then the listener for touch event added:
sprite.addEventListener(GestureEvent.DOWN, function() {
AndroidFullScreen.immersiveMode(false);
});
so immersiveMode(false) called every time user taps screen making android buttons to hide (if they were shown)

On the first users' tap we get this 'context restoring' message from Starling, and every consequent tap goes normally without this message.

It was reproduced on Android 4.4.4 and Marshmallow with AIR SDK 22 (ANE v 1.4.7) and SDK 21 (for earlier ANE builds, probably 1.4.3 or something)

**Comment by neilrackett** [comment]
Thanks for the info.

Do you see the same issue using `immersiveMode(true)`?

**Comment by metaine** [comment]
If I just switch from immersiveMode(false) to immersiveMode() the problem persists.
If I remove gesture event handling (and keep immersiveMode(false)) then no problem (but android buttons doesnt hide once revealed, I think this is expectable)

**Comment by Oldes** [comment]
What if you don't call it directly from the even function, but with a little delay?

**Comment by neilrackett** [comment]
It would be interesting to know if @Oldes suggestion works.

Using immersiveMode() will automatically re-hide the navigation bar on its own after a short delay.

I'll also have a look to see if there's a way to hide the navigation bar immediately while in immersive mode without having to re-set the display mode (which if what I'm assuming causes the loss of context).

**Comment by metaine** [comment]
"Using immersiveMode() will automatically re-hide the navigation bar on its own after a short delay" - wow! I didn't know that. So I removed tap event handler, changed immersiveMode(false) to immersiveMode() - and it works on our test devices! No lost context issue, and buttons hide automatically.

If I just add setTimeout 400 ms before immersiveMode(false) in tap event hadler - it doesnt help to avoid restoring (context). So this solution didn't work for me.

Thank you both guys for kindly helping me. I think I'd stick to "immersiveMode(true)" solution.

**Comment by neilrackett** [comment]
Glad you found a solution.
