### ISSUE TITLE
Viewport size incorrect on Simulator

### ISSUE THREAD

**Issue by cgascons** [mesmotronic/air-ane-fullscreen#35]
Hi,

I'm using this ANE and since a long time ago, we have recently updated to its last version and since we need now to set the <fullScreen> tags to false on the App Descriptor, everytime we launch the App on the Android Simulator on PC the viewport isn't initialized properly. Our stage gets cut with every different device we test it on, we create the viewport (on Starling) with the following technique:

`
/**
 * Creates the initial viewport for setting up Starling
 * */
protected function createInitialViewport(stageWidth:Number, stageHeight:Number, maxFullScreenWidth:Number, maxFullScreenHeight:Number):Rectangle
{
	return RectangleUtil.fit(new Rectangle(0, 0, stageWidth, stageHeight), new Rectangle(0, 0, maxFullScreenWidth, maxFullScreenHeight), StageScaleMode.SHOW_ALL);
}
`

Being:
'stageWidth' 640
'stageHeight' 400 (for tablets) and 360 (for phones)
And finally getting these 'maxFullScreenWidth' and 'maxFullScreenHeight' with these two methods:

`
/**
* Get the full screen width, depending on the device it will vary.
 * */
override public function getFullScreenWidth():int
{
	return (AndroidFullScreen.isImmersiveModeSupported && AndroidFullScreen.immersiveWidth > 0) ? AndroidFullScreen.immersiveWidth : stage.fullScreenWidth;
}
		
/**
 * Get the full screen height, depending on the device it will vary.
 * */
override public function getFullScreenHeight():int
{
	return (AndroidFullScreen.isImmersiveModeSupported && AndroidFullScreen.immersiveHeight > 0) ? AndroidFullScreen.immersiveHeight : stage.fullScreenHeight;
}		
`

Can you please point me in the right direction? Note: The code on the devices themselves works perfectly and the stage gets fit precisely on its position with the proper size.

Thanks,

**Comment by neilrackett** [comment]
I'll take a look to make sure the ANE is detecting and handling the simulator correctly, but please can you:

1. Confirm which version of AIR SDK you're using
1. Confirm that the simulator returns the correct values when the ANE is not used
1. Paste a copy of the settings you're using in your app descriptor

You may not need to use `immersiveWidth` and `immersiveHeight` with AIR 24, but if you do, you can shorten your code to:

* `return AndroidFullScreen.immersiveWidth || stage.fullScreenWidth`
* `return AndroidFullScreen.immersiveHeight || stage.fullScreenHeight`

**Comment by cgascons** [comment]
Absolutely:

1. Adobe AIR 24 (build 180)
2. When using <fullScreen>true</fullScreen> the values are correct.
3. Here's the details of the <initialWindow> of our app descriptor

`
<autoOrients>true</autoOrients>
<renderMode>direct</renderMode>
<depthAndStencil>true</depthAndStencil>
<fullScreen>false</fullScreen>
<visible>true</visible>
<softKeyboardBehavior>none</softKeyboardBehavior>
<aspectRatio>landscape</aspectRatio>
`

Also, I just realized something, I'm attaching a screenshot which shows one of our games with the fullscreen tag set to true (on the left) and the same game setting the fullscreen tag to true (on the right). Both screenshots were taken without using your ANE, but it shows the exact same behavior when using it (in simulator). It's like when not enabling the fullscreen the position where the buttons or navigation bar its supposed to be weren't being part of the stage.

Also, even though we are using Air 24 we are using the ANE in order to prevent the known issue stated here (https://bugbase.adobe.com/index.cfm?event=bug&id=4100625)

Thanks,

![diff](https://cloud.githubusercontent.com/assets/2189330/22326992/5514decc-e3b5-11e6-94df-ccfc73b99725.png)

**Comment by neilrackett** [comment]
I've tweaked the [1.5.0 release](https://github.com/mesmotronic/air-ane-fullscreen/releases/edit/v1.5.0) to see if that helps, but it sounds like it might be a simulator issue rather than a problem with the ANE judging by your comments.

My only other suggestion would be to wait for a `Event.ADDED_TO_STAGE` before setting the stage size, if you're not doing that already.

I've also updated the `AndroidFullScreen.fullScreenWidth` and `AndroidFullScreen.fullScreenHeight` to better handle the simulator environment, which will return the immersive width/height if supported and the stage full screen width/height if not.

**Comment by cgascons** [comment]
Hi neilrackett, 

Thanks for such a quick response. We were waiting for the `Event.ADDED_TO_STAGE` indeed, I've tried downloading the latest version of the ANE you just updated but we are experiencing the same behavior. I guess it's pretty much related to the fact of disabling the <fullScreen> tag in the app descriptor. I suppose there's no inmediate way of using this ANE without having to disable fullscreen, right?

**Comment by neilrackett** [comment]
I don't think I've actually tried starting in full screen and direct render mode with this ANE using AIR 24, so all I can suggest is giving it a go to see what happens.

I noticed that [bug 4100625](https://bugbase.adobe.com/index.cfm?event=bug&id=4100625) has been marked as fixed/closed, so it's probably worth re-reporting the issue to make sure they take another look.

**Comment by cgascons** [comment]
I believe Starling only allows the RenderMode "direct", not 100% sure about it though. 

Anyways, I'm testing now your ANE with a different configuration: just calling `AndroidFullScreen.fullScreen()` (instead of checking if immersiveMode was supported and then calling `AndroidFullScreen.immersiveMode()`) and turns out that now works fine on some devices (even with `fullScreenMode` set to false). I also found out that even having the `aspectRatio` set to `landscape`, the app was ignoring it and kind of "forcing" the `StageAspectRatio.ANY` so the app was starting in portrait. 

I've tried setting by hand `stage.setAspectRatio(StageAspectRatio.LANDSCAPE`) and now seems to be working fine on some devices, but in others it just ignores it and keeps launching the app in portrait mode (when my setup states that has to be LANDSCAPE). I know you have some examples in your code but I have found none that are exactly describes all the steps to follow.  For instance, this is what we do in our code:

`
//Assign the stage
AndroidFullScreen.stage = stage;

//Make sure the display state is NORMAL
if(stage.displayState != StageDisplayState.NORMAL)
	stage.displayState = StageDisplayState.NORMAL;

if (!AndroidFullScreen.immersiveMode())
{
	//Set state full screen interactive
	stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;
}
else
{
	//Perform the full screen mode
	AndroidFullScreen.fullScreen();	
}

//Force the aspect ratio to be LANDSCAPE
stage.setAspectRatio(StageAspectRatio.LANDSCAPE);

//Now resize the viewport
resizeViewport();
`

Does it make sense? Are we missing something? 
Thanks

**Comment by neilrackett** [comment]
The ANE should have no affect whatsoever on screen orientation, so I can't explain that issue. Does the same thing happen with the previous version of the ANE?

It doesn't look like anything's missing, but it could easily be condensed down to this with the same outcome:

```as3
AndroidFullScreen.stage = stage;
AndroidFullScreen.fullScreen();

stage.setAspectRatio(StageAspectRatio.LANDSCAPE);
resizeViewport();
```

**Comment by cgascons** [comment]
I have got rid of all the code that I had and I'm only using this now:

```
AndroidFullScreen.stage = stage;
AndroidFullScreen.fullScreen();
resizeViewport();
```

The behavior is exactly like if I wasn't using the ANE, works fine (in the device) for Android 4.4+ but the device which uses 4.1 is still showing the space for the navigation bar. I really don't know what else to try. Do I need to set the stage.scaleMode or the stage.align? Any information will be super-helpful, thanks for the support provided so far.

**Comment by neilrackett** [comment]
Have you tried the workaround that was suggested for issue #24?

**Comment by neilrackett** [comment]
Immersive mode was only introduced in Android 4.4

**Comment by cgascons** [comment]
Agreed, so, for devices running 4.1 calling `fullScreen` shouldn't be attempting to call 'leanMode' automatically? I'm now tracing the return of `fullScreen` and returns `false`.

Regarding the issue #24, shall I ignore `stage.displayState` then?

**Comment by cgascons** [comment]
Ok, just got it working. If I call `leanMode` when `fullScreen` returns false, the device behaves as expected.

**Comment by neilrackett** [comment]
Great.

`fullScreen()` will use immersive mode if it's available, and fall back to `stage.displayState = StageDisplayStage.FULL_SCREEN_INTERACTIVE` if it's not so that apps use the best available interactive full screen mode.

This is used in preference to `leanMode()`, because lean mode is non-interactive.

**Comment by cgascons** [comment]
Oh...I see, just read a little bit more and after playing around I see what you mean. Unfortunately `leanMode` doesn't help us, since the user needs to interact with the app. *sigh*
