### ISSUE TITLE
Adobe Air 64 bit support for Android

### ISSUE THREAD

**Issue by Nikos-Laskaridis** [mesmotronic/air-ane-fullscreen#36]
Any chance you will add soon 64 bit support for Android?

**Comment by neilrackett** [comment]
Yes, if we can get out hands on the AIR 33 SDK, I'd be happy to re-package it with 64-bit support added.

**Comment by neilrackett** [comment]
Updated ANE with 64-bit support is [here](https://github.com/mesmotronic/air-ane-fullscreen/blob/arm64/build/AndroidFullScreen.ane); should be treated as experimental for now.

**Comment by neilrackett** [comment]
I've added a pre-release build [here](https://github.com/mesmotronic/air-ane-fullscreen/releases), which I'll replace with an official release once AIR 33 is out of beta.

Feel free to [buy us a coffee](http://bit.ly/2UOi1Xg) if you find it useful ;-)
