### ISSUE TITLE
Xiaomi Note 7 with Android 9 - still black bands on top and bottom

### ISSUE THREAD

**Issue by PippoApps** [mesmotronic/air-ane-fullscreen#37]
Hi,
Everything seems to work fine, all methods report true.
After calling any mothod though (fullScreen, leanMode, immersiveMode) although they all return true, dimensions stay the same.
immersiveHeight is 2340, while stage.stageHeight stays 2000, and no resize is triggered.
I have followed the instructions precisely. Any hint?
Many thanks

**Comment by neilrackett** [comment]
Have you tried setting the `max_aspect`value in the `<application>` section of your manifest? e.g.

```xml
<meta-data android:name="android.max_aspect" android:value="2.16" />
```

**Comment by PippoApps** [comment]
Thank you, it did work.
