### ISSUE TITLE
You can give a simple example about this explanation.

### ISSUE THREAD

**Issue by orcuncun** [mesmotronic/air-ane-fullscreen#40]
Getting the immersive screen size
You can use the immersiveWidth and immersiveHeight properties to find out the dimensions of the screen with the system UI hidden, regardless of the current screen state.

To find out the stage size after calling fullScreen(), immersiveMode() or leanMode(), you must wait until the next RESIZE event before the stage.stageWidth and stage.stageHeight properties are updated; the properties of the Capabilities object are not updated and are therefore incorrect.

**Comment by orcuncun** [comment]
There is a gap under the long phones. How can this be resolved.

**Comment by neilrackett** [comment]
You need to set `max_aspect` in your Android manifest, see https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html
