### ISSUE TITLE
Can this ANE fix black bar caused by the notch/cutout?

### ISSUE THREAD

**Issue by Tiusami** [mesmotronic/air-ane-fullscreen#42]
My app only has a black bar in the notch area. Unfortunately, I need an ANE to fix it. Would this thing do the trick?

**Comment by neilrackett** [comment]
Have you tried the solution in #37 ?

**Comment by Tiusami** [comment]
I have it defined at 2.8 I believe. I haven't tested your ANE yet, but I'm planning to do it today, so I'll let you know if this thing solves the problem.

Basically, we need to enable the short_edges mode on android:

You can set the cutout mode either programmatically or by setting a style in your activity. The example below defines a style that you can use to apply the LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES attribute to the activity.

<style name="ActivityTheme">
  <item name="android:windowLayoutInDisplayCutoutMode">
    shortEdges 
  </item>
</style>

**Comment by Tiusami** [comment]
I'm using a different extension that enables me to set CutoutMode to short edges.

**Comment by neilrackett** [comment]
Thanks for letting us know -- which extension did you use?

**Comment by Tiusami** [comment]
I used 'Air Android Utils by marpies'.
